name: 'RaylibSetup'
description: 'Setup a raylib environment'
runs:
  using: "composite"
  steps:
    - name: Dependencies-Linux
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
  
    - name: Upgrade brew
      if: runner.os == 'macOS'
      env:
        HOMEBREW_NO_ANALYTICS: 1
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      shell: bash
      run: |
        echo "::group::brew update" && brew update && echo "::endgroup::"
        echo "::group::brew bundle" && brew bundle && echo "::endgroup::"
        echo "::group::brew config" && brew config && echo "::endgroup::"

    - name: Add msbuild to PATH
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.0.3
      
    - name: Git Checkout
      uses: actions/checkout@v2
      with:
        repository: raysan5/raylib
        
    - name: Install
      shell: bash
      run: |
        cd src
        make PLATFORM=PLATFORM_DESKTOP
        
    - name: Leave setup directory
      shell: bash
      run: |
        cd ../..
