name: 'RaylibSetup'
description: 'Setup a raylib environment'
runs:
  using: "composite"
  steps:
    - name: Dependencies
      shell: bash
      run: sudo apt install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
  
    - name: Git Checkout
      uses: actions/checkout@v2
      with:
        repository: raysan5/raylib
        
    - name: Install
      shell: bash
      run: |
        cd src
        make PLATFORM=PLATFORM_DESKTOP
        sudo make install
        
    - name: Leave setup directory
      shell: bash
      run: |
        cd ../..
