# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Test

on:
  workflow_dispatch:
  push:
    branches: ["master", "main"]
    paths-ignore:
    - '**/*.md'
  pull_request:

jobs:
  test:
    if: success()
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup
        uses: ./
