# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Test

on:
  workflow_dispatch:
  push:
    branches: ["master", "main"]
    paths-ignore:
    - '**/*.md'
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest 
          - macos-latest 
          - windows-latest

    steps:
      # Checkout necessary files to run next action
      - uses: actions/checkout@v2

      - name: Test
        uses: ./
